[package]
name = "paimon-libusb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

build = "build.rs"

[dependencies]
libc = "0.2.139"

[build-dependencies]
cc = "1.0"
pkg-config = "0.3"